# Generated by Django 3.0.8 on 2020-08-12 17:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mandal', '0001_initial'),
        ('PHC', '0001_initial'),
        ('village', '0001_initial'),
        ('village_sec', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='PVGT',
            new_name='PVTG',
        ),
        migrations.AddField(
            model_name='patient',
            name='BasicSymptoms',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='BasicVitals',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='hb',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='patient',
            name='mandal',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_status',
            field=models.CharField(default='Closed', max_length=50),
        ),
         migrations.AddField(
            model_name='patient',
            name='phc',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='report',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='villagesec',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='patient',
            name='type_data',
            field=models.CharField(default='Production', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='village',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='village.Village'),
        ),
    ]
