# Generated by Django 3.0.8 on 2020-08-12 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20200812_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='phc',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='villagesec',
        ),
    ]
