# Generated by Django 3.0.8 on 2020-08-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20200812_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='mandal',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='phc',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='villagesec',
            field=models.CharField(default='', max_length=50),
        ),
    ]
