# Generated by Django 3.0.8 on 2020-08-13 14:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_auto_20200813_0601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='status',
            new_name='ref_status',
        ),
        migrations.AddField(
            model_name='patient',
            name='diffrential_count',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='wbc_count',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='hb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='type_data',
            field=models.CharField(default='Development', max_length=50),
        ),
    ]
