# Generated by Django 3.0.8 on 2020-08-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_auto_20200813_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='plat_count',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
