# Generated by Django 3.0.8 on 2020-08-13 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mandal', '0001_initial'),
        ('village_sec', '0001_initial'),
        ('village', '0001_initial'),
        ('PHC', '0001_initial'),
        ('patient', '0009_patient_plat_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mandal',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mandal.Mandal'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phc',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='PHC.PHC'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='village',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='village.Village'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='villagesec',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='village_sec.Village_sec'),
        ),
    ]
