# Generated by Django 3.0.8 on 2020-08-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_auto_20200813_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='maritalstatus',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
